services:
  php:
    build:
      context: ./docker/php-fpm
    container_name: cv-richi-symfony-php-fpm
    volumes:
      - ./symfony-app:/var/www/html
    networks:
      - app-network
  nginx:
    image: nginx:alpine
    container_name: cv-richi-symfony-nginx
    ports:
      - "${HTTP_HOST_PORT}:80"
      - "${HTTPS_HOST_PORT}:443"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./symfony-app:/var/www/html
    depends_on:
      - php
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
